apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
  labels:
    app: probes-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: probes-demo
  template:
     metadata:
       labels:
         app: probes-demo
     spec:
       containers:
         - name: probes-demo
           image: k8s-health-and-readiness
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 8080
           livenessProbe:
             httpGet:
               path: /healthz
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
           readinessProbe:
             httpGet:
               path: /readiness
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
