apiVersion: v1
kind: Service
metadata:
  name: probes-demo
  labels:
    app: probes-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: probes-demo
  type: ClusterIP
